import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Header.module.css";
import { Typography, Box, Button, Avatar, Link } from "@mui/material";
import Caraousel from "../components/Caraousel";
import Aptitude from "../components/Aptitude";
import Forms from "../components/Forms";
import Footer from "../components/Footer";

export default function Home() {
  const handleTop = () => {
    window.scrollTo({
      top: 0,
      behavior: "smooth",
    });
  };

  return (
    <Box>
      <Head>
        <title>Curriculum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <Box className={styles.Box}>
        <Button
          sx={{ right: "88%", fontSize: "1.2vw" }}
          variant="text"
          size="large"
          onClick={handleTop}
        >
          INICIO
        </Button>
        <Link
          href="https://www.dropbox.com/s/soo9ipt9bye09gj/CV.pdf?dl=0"
          target="_blank"
          rel="noreferrer noopener"
        >
          <Button
            sx={{ left: "80%", width: "20%" }}
            variant="outlined"
            size="large"
          >
            DESCARGAR MI CV COMPLETO
          </Button>
        </Link>
        <Image src={"/Code.jpg"} width="100%" height="53%" layout="responsive" />
        <Avatar
          className={styles.Avatar}
          alt="Heli Rosales"
          src="/Avatar.jpg"
          sx={{ width: "21%", height: "40%" }}
          style={{
            border: "10px solid lightgray",
          }}
        />
        <Typography variant="h1" sx={{ fontWeight: 500 }}>
          Heli Rosales
        </Typography>
        <Typography variant="h2" sx={{ fontWeight: "bold" }}>
          Frontend Developer
        </Typography>
      </Box>
      <Caraousel />
      <Aptitude />
      <Forms />
      <Footer />
    </Box>
  );
}
